import { useState } from "react";
import { generateDemoReport, generateLiveReport } from "../services/api";
import type {
  IntelligenceReport,
  IntelligenceRequest,
} from "../types/intelligence";
import {
  Search,
  ShieldAlert,
  TrendingUp,
  Activity,
  ExternalLink,
  Sparkles,
  Download,
  Copy,
} from "lucide-react";

export default function Dashboard() {
  const [companyName, setCompanyName] = useState("Datadog");
  const [companyWebsite, setCompanyWebsite] = useState(
    "https://www.datadoghq.com"
  );
  const [competitors, setCompetitors] = useState("New Relic, Dynatrace");
  const [track, setTrack] = useState("GTM Intelligence");
  const [monitoringGoal, setMonitoringGoal] = useState(
    "Monitor competitor positioning, hiring signals, pricing movement, and market opportunities."
  );

  const [report, setReport] = useState<IntelligenceReport | null>(null);
  const [loading, setLoading] = useState(false);
  const [lastMode, setLastMode] = useState<"demo" | "live" | null>(null);

  const buildRequest = (): IntelligenceRequest => {
    return {
      companyName,
      companyWebsite,
      competitors: competitors
        .split(",")
        .map((item) => item.trim())
        .filter(Boolean),
      track,
      monitoringGoal,
    };
  };

  const handleGenerate = async () => {
    try {
      setLoading(true);
      setLastMode("demo");

      const result = await generateDemoReport(buildRequest());
      setReport(result);
    } catch (error: any) {
      console.error("API ERROR:", error);

      alert(
        error?.response?.data
          ? JSON.stringify(error.response.data)
          : error?.message || "Unknown error"
      );
    } finally {
      setLoading(false);
    }
  };

  const handleGenerateLive = async () => {
    try {
      setLoading(true);
      setLastMode("live");

      const result = await generateLiveReport(buildRequest());
      setReport(result);
    } catch (error: any) {
      console.error("LIVE API ERROR:", error);

      alert(
        error?.response?.data
          ? JSON.stringify(error.response.data)
          : error?.message || "Unknown error"
      );
    } finally {
      setLoading(false);
    }
  };

  const buildMarkdownReport = () => {
    if (!report) return "";

    const generatedAt = new Date(report.generatedAt).toLocaleString();

    const signalsMarkdown = report.signals
      .map(
        (signal, index) => `
  ### Signal ${index + 1}: ${signal.title}

  - Type: ${signal.signalType}
  - Source: ${signal.source}
  - Confidence: ${signal.confidenceScore}%
  - URL: ${signal.url}

  ${signal.summary}
  `
      )
      .join("\n");

    const actionsMarkdown = report.recommendedActions
      .map((action, index) => `${index + 1}. ${action}`)
      .join("\n");

    return `# SignalWatch AI Intelligence Report

  ## Company
  ${report.companyName}

  ## Track
  ${report.track}

  ## Generated At
  ${generatedAt}

  ## Executive Summary
  ${report.executiveSummary}

  ## Scores

  - Risk Score: ${report.riskScore}/100
  - Opportunity Score: ${report.opportunityScore}/100

  ## Detected Signals

  ${signalsMarkdown}

  ## Recommended Actions

  ${actionsMarkdown}

  ---

  Generated by SignalWatch AI using Bright Data live web data and Gemini AI analysis.
  `;
  };

  const handleExportMarkdown = () => {
    if (!report) return;

    const markdown = buildMarkdownReport();
    const blob = new Blob([markdown], {
      type: "text/markdown;charset=utf-8",
    });

    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");

    const safeCompanyName = report.companyName
      .replace(/[^a-z0-9]/gi, "-")
      .toLowerCase();

    link.href = url;
    link.download = `signalwatch-${safeCompanyName}-report.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  };

  const handleCopySummary = async () => {
    if (!report) return;

    const text = `SignalWatch AI Report - ${report.companyName}

  ${report.executiveSummary}

  Risk Score: ${report.riskScore}/100
  Opportunity Score: ${report.opportunityScore}/100

  Top Recommended Actions:
  ${report.recommendedActions.map((action, index) => `${index + 1}. ${action}`).join("\n")}
  `;

    try {
      await navigator.clipboard.writeText(text);
      alert("Executive summary copied to clipboard.");
    } catch (error) {
      console.error("Copy failed:", error);
      alert("Copy failed. Please try again.");
    }
  };

  return (
    <div className="min-h-screen bg-slate-950 text-white">
      <header className="border-b border-white/10 bg-slate-950/80 px-8 py-6">
        <div className="mx-auto max-w-7xl">
          <p className="text-sm uppercase tracking-[0.35em] text-cyan-300">
            Web Data UNLOCKED Hackathon
          </p>

          <h1 className="mt-3 text-4xl font-bold tracking-tight">
            SignalWatch AI
          </h1>

          <p className="mt-3 max-w-3xl text-slate-300">
            Live web intelligence agent for GTM, finance, and security teams.
            Built to monitor public web signals, detect risks, and generate
            executive-ready intelligence reports.
          </p>

          <div className="mt-5 flex flex-wrap gap-3 text-sm">
            <span className="rounded-full border border-cyan-300/20 bg-cyan-300/10 px-4 py-2 text-cyan-200">
              Powered by Bright Data SERP API
            </span>

            <span className="rounded-full border border-purple-300/20 bg-purple-300/10 px-4 py-2 text-purple-200">
              Analyzed with Gemini AI
            </span>

            <span className="rounded-full border border-emerald-300/20 bg-emerald-300/10 px-4 py-2 text-emerald-200">
              Enterprise Intelligence Agent
            </span>
          </div>
        </div>
      </header>

      <main className="mx-auto grid max-w-7xl gap-8 px-8 py-8 lg:grid-cols-[420px_1fr]">
        <section className="rounded-3xl border border-white/10 bg-white/5 p-6 shadow-2xl">
          <div className="mb-6 flex items-center gap-3">
            <div className="rounded-2xl bg-cyan-400/20 p-3 text-cyan-300">
              <Search size={22} />
            </div>

            <div>
              <h2 className="text-xl font-semibold">
                Create Intelligence Report
              </h2>

              <p className="text-sm text-slate-400">
                Generate demo data or collect live web intelligence using Bright
                Data SERP API.
              </p>
            </div>
          </div>

          <div className="space-y-4">
            <label className="block">
              <span className="text-sm text-slate-300">Company name</span>
              <input
                value={companyName}
                onChange={(e) => setCompanyName(e.target.value)}
                className="mt-2 w-full rounded-2xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"
              />
            </label>

            <label className="block">
              <span className="text-sm text-slate-300">Company website</span>
              <input
                value={companyWebsite}
                onChange={(e) => setCompanyWebsite(e.target.value)}
                className="mt-2 w-full rounded-2xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"
              />
            </label>

            <label className="block">
              <span className="text-sm text-slate-300">
                Competitors, separated by comma
              </span>
              <input
                value={competitors}
                onChange={(e) => setCompetitors(e.target.value)}
                className="mt-2 w-full rounded-2xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"
              />
            </label>

            <label className="block">
              <span className="text-sm text-slate-300">Track</span>
              <select
                value={track}
                onChange={(e) => setTrack(e.target.value)}
                className="mt-2 w-full rounded-2xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"
              >
                <option>GTM Intelligence</option>
                <option>Finance & Market Intelligence</option>
                <option>Security & Compliance</option>
              </select>
            </label>

            <label className="block">
              <span className="text-sm text-slate-300">Monitoring goal</span>
              <textarea
                value={monitoringGoal}
                onChange={(e) => setMonitoringGoal(e.target.value)}
                rows={5}
                className="mt-2 w-full rounded-2xl border border-white/10 bg-slate-900 px-4 py-3 outline-none focus:border-cyan-300"
              />
            </label>

            <div className="grid gap-3 pt-2">
              <button
                type="button"
                onClick={handleGenerate}
                disabled={loading}
                className="w-full rounded-2xl bg-slate-800 px-5 py-4 font-semibold text-white transition hover:bg-slate-700 disabled:cursor-not-allowed disabled:opacity-60"
              >
                {loading && lastMode === "demo"
                  ? "Generating demo report..."
                  : "Generate Demo Report"}
              </button>

              <button
                type="button"
                onClick={handleGenerateLive}
                disabled={loading}
                className="w-full rounded-2xl bg-cyan-300 px-5 py-4 font-semibold text-slate-950 transition hover:bg-cyan-200 disabled:cursor-not-allowed disabled:opacity-60"
              >
                {loading && lastMode === "live"
                  ? "Collecting live web data..."
                  : "Generate Live Bright Data Report"}
              </button>
            </div>

            <div className="rounded-2xl border border-cyan-300/10 bg-cyan-300/5 px-4 py-3 text-sm text-slate-300">
              <span className="font-semibold text-cyan-300">Live mode:</span>{" "}
              collects public search signals through Bright Data and converts
              them into business intelligence cards.
            </div>
          </div>
        </section>

        <section className="space-y-6">
          {!report && (
            <div className="rounded-3xl border border-dashed border-white/15 bg-white/5 p-10 text-center">
              <Activity className="mx-auto mb-4 text-cyan-300" size={42} />

              <h2 className="text-2xl font-semibold">
                No report generated yet
              </h2>

              <p className="mt-3 text-slate-400">
                Fill the form and generate your first intelligence report.
              </p>
            </div>
          )}

          {report && (
            <>
              <div className="rounded-3xl border border-white/10 bg-white/5 p-6">
                <div className="flex flex-wrap items-center justify-between gap-3">
                  <p className="text-sm uppercase tracking-[0.25em] text-cyan-300">
                    Executive Summary
                  </p>

                  <span className="inline-flex items-center gap-2 rounded-full border border-cyan-300/20 bg-cyan-300/10 px-3 py-1 text-xs font-semibold text-cyan-300">
                    <Sparkles size={14} />
                    {lastMode === "live"
                      ? "Live Bright Data Report"
                      : "Demo Report"}
                  </span>
                </div>

                <h2 className="mt-3 text-3xl font-bold">
                  {report.companyName}
                </h2>

                <p className="mt-4 text-slate-300">
                  {report.executiveSummary}
                </p>

                <p className="mt-4 text-xs text-slate-500">
                  Generated at:{" "}
                  {new Date(report.generatedAt).toLocaleString()}
                </p>

                <div className="mt-5 flex flex-wrap gap-3">
                  <button
                    type="button"
                    onClick={handleExportMarkdown}
                    className="inline-flex items-center gap-2 rounded-2xl bg-cyan-300 px-4 py-3 text-sm font-semibold text-slate-950 transition hover:bg-cyan-200"
                  >
                    <Download size={16} />
                    Export Markdown Report
                  </button>

                  <button
                    type="button"
                    onClick={handleCopySummary}
                    className="inline-flex items-center gap-2 rounded-2xl border border-white/10 bg-slate-900 px-4 py-3 text-sm font-semibold text-white transition hover:border-cyan-300/30 hover:bg-slate-800"
                  >
                    <Copy size={16} />
                    Copy Executive Summary
                  </button>
                </div>
              </div>

              <div className="grid gap-6 md:grid-cols-2">
                <div className="rounded-3xl border border-white/10 bg-white/5 p-6">
                  <div className="flex items-center gap-3">
                    <ShieldAlert className="text-rose-300" />
                    <h3 className="text-lg font-semibold">Risk Score</h3>
                  </div>

                  <p className="mt-5 text-5xl font-bold">
                    {report.riskScore}
                  </p>

                  <p className="mt-2 text-sm text-slate-400">
                    Lower is better
                  </p>
                </div>

                <div className="rounded-3xl border border-white/10 bg-white/5 p-6">
                  <div className="flex items-center gap-3">
                    <TrendingUp className="text-emerald-300" />
                    <h3 className="text-lg font-semibold">
                      Opportunity Score
                    </h3>
                  </div>

                  <p className="mt-5 text-5xl font-bold">
                    {report.opportunityScore}
                  </p>

                  <p className="mt-2 text-sm text-slate-400">
                    Higher is better
                  </p>
                </div>
              </div>

              <div className="rounded-3xl border border-white/10 bg-white/5 p-6">
                <div className="flex flex-wrap items-center justify-between gap-3">
                  <h3 className="text-xl font-semibold">Detected Signals</h3>

                  <span className="rounded-full bg-white/5 px-3 py-1 text-sm text-slate-400">
                    {report.signals.length} signals found
                  </span>
                </div>

                {report.signals.length === 0 && (
                  <div className="mt-5 rounded-2xl border border-yellow-300/20 bg-yellow-300/10 p-5 text-yellow-100">
                    No live signals were found. Try another company, competitor,
                    or monitoring goal.
                  </div>
                )}

                {report.signals.length > 0 && (
                  <div className="mt-5 space-y-4">
                    {report.signals.map((signal, index) => (
                      <article
                        key={`${signal.url}-${index}`}
                        className="rounded-2xl border border-white/10 bg-slate-900 p-5 transition hover:border-cyan-300/30 hover:bg-slate-900/80"
                      >
                        <div className="flex flex-wrap items-start justify-between gap-3">
                          <div>
                            <p className="mb-2 text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">
                              Signal #{index + 1}
                            </p>

                            <h4 className="text-lg font-semibold">
                              {signal.title}
                            </h4>
                          </div>

                          <span className="rounded-full bg-cyan-300/10 px-3 py-1 text-sm text-cyan-300">
                            {signal.signalType}
                          </span>
                        </div>

                        <p className="mt-3 text-slate-300">
                          {signal.summary}
                        </p>

                        {signal.url && (
                          <a
                            href={signal.url}
                            target="_blank"
                            rel="noreferrer"
                            className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-cyan-300 transition hover:text-cyan-200"
                          >
                            Open source
                            <ExternalLink size={15} />
                          </a>
                        )}

                        <div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-white/10 pt-4 text-sm text-slate-400">
                          <span>{signal.source}</span>
                          <span>Confidence: {signal.confidenceScore}%</span>
                        </div>
                      </article>
                    ))}
                  </div>
                )}
              </div>

              <div className="rounded-3xl border border-white/10 bg-white/5 p-6">
                <h3 className="text-xl font-semibold">Recommended Actions</h3>

                <ul className="mt-5 space-y-3">
                  {report.recommendedActions.map((action, index) => (
                    <li
                      key={index}
                      className="rounded-2xl border border-white/10 bg-slate-900 px-4 py-3 text-slate-300"
                    >
                      <span className="mr-2 font-semibold text-cyan-300">
                        {index + 1}.
                      </span>
                      {action}
                    </li>
                  ))}
                </ul>
              </div>
            </>
          )}
        </section>
      </main>
    </div>
  );
}